Tue, 23 Aug 2016 12:44:46 classify_server.py[line:136] INFO Starting classify server...
Tue, 23 Aug 2016 12:44:53 classify_server.py[line:104] ERROR object of type 'bool' has no len()
Tue, 23 Aug 2016 12:51:58 classify_server.py[line:138] INFO Starting classify server...
Tue, 23 Aug 2016 12:52:03 classify_server.py[line:106] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 02:38:36 classify_server.py[line:138] INFO Starting classify server...
Wed, 24 Aug 2016 02:38:49 classify_server.py[line:106] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 02:41:19 classify_server.py[line:138] INFO Starting classify server...
Wed, 24 Aug 2016 02:41:54 classify_server.py[line:106] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 02:56:42 classify_server.py[line:140] INFO Starting classify server...
Wed, 24 Aug 2016 02:56:49 classify_server.py[line:108] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 02:58:04 classify_server.py[line:144] INFO Starting classify server...
Wed, 24 Aug 2016 02:58:08 classify_server.py[line:112] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 03:03:00 classify_server.py[line:142] INFO Starting classify server...
Wed, 24 Aug 2016 03:03:05 classify_server.py[line:110] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 03:13:43 classify_server.py[line:139] INFO Starting classify server...
Wed, 24 Aug 2016 03:13:48 classify_server.py[line:107] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 03:19:29 classify_server.py[line:140] INFO Starting classify server...
Wed, 24 Aug 2016 03:19:33 classify_server.py[line:107] ERROR object of type 'bool' has no len()
Wed, 24 Aug 2016 03:22:38 classify_server.py[line:140] INFO Starting classify server...
Wed, 24 Aug 2016 03:22:45 classify_server.py[line:79] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 03:22:45 classify_server.py[line:107] ERROR global name 'res_dict' is not defined
Wed, 24 Aug 2016 06:35:12 classify_server.py[line:139] INFO Starting classify server...
Wed, 24 Aug 2016 06:35:27 classify_server.py[line:79] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:37:14 classify_server.py[line:137] INFO Starting classify server...
Wed, 24 Aug 2016 06:40:09 classify_server.py[line:77] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:42:01 classify_server.py[line:139] INFO Starting classify server...
Wed, 24 Aug 2016 06:42:05 classify_server.py[line:77] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:43:37 classify_server.py[line:141] INFO Starting classify server...
Wed, 24 Aug 2016 06:43:41 classify_server.py[line:108] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:45:45 classify_server.py[line:143] INFO Starting classify server...
Wed, 24 Aug 2016 06:45:51 classify_server.py[line:110] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:47:40 classify_server.py[line:144] INFO Starting classify server...
Wed, 24 Aug 2016 06:47:46 classify_server.py[line:111] ERROR 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
Wed, 24 Aug 2016 06:48:28 classify_server.py[line:144] INFO Starting classify server...
Wed, 24 Aug 2016 06:48:36 classify_server.py[line:111] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:52:33 classify_server.py[line:145] INFO Starting classify server...
Wed, 24 Aug 2016 06:52:37 classify_server.py[line:112] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:53:14 classify_server.py[line:147] INFO Starting classify server...
Wed, 24 Aug 2016 06:53:18 classify_server.py[line:114] ERROR get_word_vec failed: unknown result
Wed, 24 Aug 2016 06:55:03 classify_server.py[line:147] INFO Starting classify server...
Wed, 24 Aug 2016 07:33:50 classify_server.py[line:140] INFO Starting classify server...
Wed, 24 Aug 2016 07:47:13 classify_server.py[line:146] INFO Starting classify server...
Wed, 24 Aug 2016 07:48:15 classify_server.py[line:146] INFO Starting classify server...
Wed, 24 Aug 2016 07:48:35 classify_server.py[line:146] INFO Starting classify server...
